### PR TITLE
build: filled forest client

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
All the pub(crate) -> pub is due to compilation errors, caused by committer client

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132#-:-NyVddTs3YjoLPZ0f6WD:bab63a2)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVdCPV8Sioz9G6hKB0:-NyVdCPV8Sioz9G6hKB1:b-25hnjs) ([raw file](https://github.com/starkware-libs/committer/blob/6263ae6395dab4aa2275c3e6e484d6f0cf09c6f7/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L11)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) trait ForestToPython<L: LeafData, T: FilledTree<L>> {
> ```

Need trait and not just impl, since it is outside the crate in which filled forest defined ( compiler demand).

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/felt.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVgE7t3zxQePg3iRwf:-NyVgE7t3zxQePg3iRwg:b20473e) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer/src/felt.rs#L101)):*
> ```XML
>     pub fn to_string(&self) -> Result<String, serde_json::Error> {
>         serde_json::to_string(&self.to_bytes_be().to_vec())
>     }
> ```

please move this utility to the CLI crate... it is only for python + we already have two self->String converters here, it is getting confusing



_Code quote:_
```XML
    pub fn to_string(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(&self.to_bytes_be().to_vec())
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVeoi-4vwRsFX_X2Dx:-NyVeoi-4vwRsFX_X2Dy:byewgez) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L27)):*
> ```XML
> /// FilledTree consists of all nodes which were modified in the update, including their updated
> /// data and hashes.
> #[allow(async_fn_in_trait)]
> ```

why is this needed only now?



_Code quote:_
```XML
#[allow(async_fn_in_trait)]
```
___
*[`crates/committer_cli/src/main.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVgM732FyDOPPtAHZ2:-NyVgM732FyDOPPtAHZ3:b-mqh0ku) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/main.rs#L7)):*
> ```XML
> pub mod parse_input;
> pub mod tests;
> pub mod patricia_merkle_tree;
> ```

why is this the name of the module?
it is only for serialization, please rename to `filled_tree_output` or something more specific



_Suggestion:_
```XML
filled_tree_output
```
___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVff3gDL-xV556ScZI:-NyVff3gDL-xV556ScZJ:b-rdse4b) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L19)):*
> ```XML
>         let mut storage: MapStorage = MapStorage {
>             storage: HashMap::new(),
>         };
> ```

1. you can pass non-mut variables as `&mut`
2. add `#[derive(Default)]` on `MapStorage` and you should be able to remove the redundant init code; if not, add an `impl MapStorage` block with a `pub fn new() -> Self` function



_Suggestion:_
```XML
        let storage = MapStorage::default();
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVeoi-4vwRsFX_X2Dx:-NyVgu4N4O-1ef9r9p47:b7gu07y) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed only now?
</blockquote></details>

Since I changed the trait to be public.
___
*[`crates/committer_cli/src/main.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVgM732FyDOPPtAHZ2:-NyVhXo_AWDfvCuPPdze:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/main.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this the name of the module?
it is only for serialization, please rename to `filled_tree_output` or something more specific
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVff3gDL-xV556ScZI:-NyVjNOrBpAzIiGFX5LA:bwawe3y) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. you can pass non-mut variables as `&mut`
2. add `#[derive(Default)]` on `MapStorage` and you should be able to remove the redundant init code; if not, add an `impl MapStorage` block with a `pub fn new() -> Self` function
</blockquote></details>

I'm not sure I understand 1. If I remove the mut from the snippet, it won't compile.



_Code snippet:_
```XML
let mut storage = MapStorage::default();
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVeoi-4vwRsFX_X2Dx:-NyVuzuhAvE1STrtES3X:bpkin04) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L27)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Since I changed the trait to be public.
</blockquote></details>

please use the suggested solution [here](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#async-fn-in-public-traits): i.e. use `trait_variant::make`.
the linter exposes a real problem if we make this trait part of public API.
___
*[`crates/committer_cli/src/main.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVgM732FyDOPPtAHZ2:-NyVvCtq2KfghMHTu7QE:b-irwhab) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/main.rs#L7)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where?
___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVff3gDL-xV556ScZI:-NyVvSLQ4fhn7vfP9rqn:b-i5gw7z) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L19)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I'm not sure I understand 1. If I remove the mut from the snippet, it won't compile.
</blockquote></details>

ah right, my mistake.
ignore 1, please do 2 though

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r5, 28 of 28 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVff3gDL-xV556ScZI:-Ny_OWSM90C84ipGGMt2:bb5f1lo) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L19)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where? (2) is still missing

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/committer/132#-NyVff3gDL-xV556ScZI:-Ny_StJNAjMlNFPuxGin:bjckj8e) ([raw file](https://github.com/starkware-libs/committer/blob/543d39e43c966cf6e38dbea3f495c839c1570830/crates/committer_cli/src/patricia_merkle_tree/filled_forest.rs#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where? (2) is still missing
</blockquote></details>

I accidentally deleted it in the new commit.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/132#-:-Ny_c_Ok2YWlC1APG0ku:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)
